### ISSUE TITLE
Specify how the matching is done

### ISSUE THREAD

**Issue by lubianat** [jvfe/paper_wdt_panglao#6]
Some questions:

How does the reconciler work? 
What is the role of Open Refine (maybe a citation would fit)?
Manual analyses was used for figures?
Were pseudogenes also considered?

Maybe we can provide exactly what was done here, with code snippets and so on. Maybe we can even embedd the Python script somehow (not runnable, but scrollable or something). What do you thin, @jvfe ?

**Comment by jvfe** [comment]
In this case, it uses the [Wikidata reconciliation API](https://wikidata.reconci.link/) to do the matches, but it serves as a Python interface to W3C reconciliation services.

Not exactly OpenRefine, but it would be good to cite the [W3C reconciliation API spec](https://reconciliation-api.github.io/specs/latest/), it's just something I totally forgot to do. I'll make a commit soon citing both this and Wikidata's reconc. service and hopefully clearing things up.

All figures were made with code that is available in the source code repo.

Not sure I understood, where do you mean the pseudogenes would be included?

All code I used is available in the source code repo as a package, simple scripts that use this package, and tests for said package. Not sure embedding a python script would get the point across since there are external functions, so the snippet could end up being too big.

**Comment by lubianat** [comment]
Nice, cool. 

Some pseudogenes on Wikidata are listed on Panglao as markers (what is weird, maybe worth discussing actually, as these are either very interesting to look at, or clear false positives in the database). [Example](https://www.wikidata.org/wiki/Q18050637) with a P31 gene too. I remember there were some listed only as pseudogenes. The idea was: if a gene was listed as P31 pseudogene, would we catch ?But that is minor, so yeah, forget about it. 

About the script, yeah, true. Maybe a link to a permanent version of the scripts here and there, then? Just to make it extra-easy if anyone wants to take a look (like me in 3 years lol) 

One thing that we can do is to invite someone from Gene Wiki to join us in the writing part for better discussion on genes and stuff.

**Comment by jvfe** [comment]
Huh, I didn't know that about the pseudogenes, it's certainly something I didn't account for. The query I used as a matching point for the genes was a query composed exclusively of genes (Q7187) - it's linked in the paper if you wanna see, so they probably weren't considered. This is something I can add to the manuscript later, too.

In regards to the script, probably the best option would be for me to make a release (e.g. tag) of the source code repo and archive it in zenodo, I think it's adequate. I'll get to that soon.

Sure, no problem!
